### PR TITLE
Janky Stuff That Shouldn't Exist

### PR DESCRIPTION
**Pull request by VolatileIvory**
I have no idea why I'm making a pull request for this, but I have nothing to lose so why not? Basically, I've been fiddling with some duplicated attachments from Decay and Renewal and managed to cobble together these four abominations of attachments. They have some vague potential and may eventually be good enough for the main repository, but if I keep trying to fix them on my own it'll take decades. Feel free to criticize as much as you like, this is entirely just the product of my unskilled boredom and I have no expectations for anyone to take it seriously although as much constructiveness as is possible with this disaster I've spawned would be appreciated.

### CODE REVIEW

**Comment by Fesiug** [comment]
see if you can't get them in UC Extras

**Comment by Fesiug** [comment]
this IS uc extras, Fuck

**Comment by Fesiug** [comment]
this IS uc extras, Fuck

**Comment by VolatileIvory** [comment]
Still haven't figured out how to make the RAS-12 receiver accept shotgun ammo yet, some help with that would be great.

**Comment by Fesiug** [comment]
To allow the RAS-12 to use shotgun ammo types, you would have to manually modify the M16's base code, which we cannot do in Extras.

**Comment by VolatileIvory** [comment]
Well, fuck. Janky option it is I guess.

**Comment by Sninctbur** [comment]
> Still haven't figured out how to make the RAS-12 receiver accept shotgun ammo yet, some help with that would be great.

All you need to do is set att.Override_IsShotgun to true in the RAS-12 attachment file. The UC ammo type attachments have been updated to use the same slot, but change whether they are accessible or not depending on if the weapon is considered a shotgun. (This all assumes that the system hasn't been broken yet.)

**Comment by VolatileIvory** [comment]
> > Still haven't figured out how to make the RAS-12 receiver accept shotgun ammo yet, some help with that would be great.
> 
> All you need to do is set att.Override_IsShotgun to true in the RAS-12 attachment file. The UC ammo type attachments have been updated to use the same slot, but change whether they are accessible or not depending on if the weapon is considered a shotgun. (This all assumes that the system hasn't been broken yet.)

I tried that, but it didn't do anything for some reason. It didn't even allow shotgun muzzle attachments. You might be able to fish around in the code for what I no doubt got wrong, but the attachment idea was pretty flawed in the first place so go ahead and leave it if you'd rather not waste time on it.

**Comment by VolatileIvory** [comment]
Upon further examination the AKM's shotgun conversion has the same problem, so it may be a problem with the shared content.

**Comment by Fesiug** [comment]
I'll look into it.

**Comment by Fesiug** [comment]
Oh wait, you need the latest version of the ArcCW base on GitHub right now. Do you have it? @VolatileIvory

**Comment by VolatileIvory** [comment]
No, I'm an idiot and I use the workshop version. I'll update now that I know it's a problem though.

**Comment by VolatileIvory** [comment]
The latest attachment (AK-9 receiver) is kinda stupidly overpowered, and I have no idea how to fix it without it being even more unrealistic than it probably is already because I got all my information from Wikipedia. Any help with rebalancing would be appreciated.

**Comment by Taskmer** [comment]
The Uzi pistol frame is unnecessary as you can just use the competition internals and achieve a very similar effect. And sabotaged ammo seems silly too, my idea of Urban Coalition Extras is that things can fit small niches but they have to actually have some use. Better of as a standalone mod for those who really do want it. Sorry dear.

**Pull request closed without merging**
